// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_path_ from "./routes/[...path].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $clear360 from "./routes/clear360.tsx";
import * as $index from "./routes/index.tsx";
import * as $sitemap_xml from "./routes/sitemap.xml.tsx";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[...path].tsx": $_path_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/clear360.tsx": $clear360,
    "./routes/index.tsx": $index,
    "./routes/sitemap.xml.tsx": $sitemap_xml,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
